#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          chrootbooter
# Should-Start:      $local_fs $remote_fs $network $named $time
# Should-Stop:       $local_fs $remote_fs $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop chroot "virtual machines"
# Description:       Controls the chroot "virtual machines" boot
### END INIT INFO

case "$1" in
start)
  echo "Starting chroot \"virtual machines\"..."
  chrootbooter start
  echo " done."
  ;;
restart|force-reload)
  /etc/init.d/chrootbooter.sh stop
  /etc/init.d/chrootbooter.sh start
  ;;
stop)
  echo "Stopping chroot \"virtual machines\"..."
  chrootbooter stop
  echo " done."
  ;;
*)
  echo "Usage: /etc/init.d/chrootbooter {start|stop|restart|force-reload}"
  exit 1
  ;;
esac

exit 0
