# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         chrootbooter
version:      0.03
version_from: script/chrootbooter
installdirs:  site
requires:
    Config::Tiny:                  1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
